### ISSUE TITLE
Erro composer.json

### ISSUE THREAD

**Issue by marciocelebri** [artesaos/laravel-installer#3]
Após instalar e configurar o composer global, quando rodo o comando laravel new blog 5.1 dá um erro que no diretório www/html (apache) não tem o arquivo composer.json.

**Comment by mauri870** [comment]
Provavelmente seja algo com a permissão da pasta... É possível que seja um bug inclusive, pois ele deveria abortar a instalação mas ao que parece ele continua para a parte que executa a instalação das dependências, não encontra o composer.json e acusa o erro na instalação.
Veja se consegue ceder permissão de escrita para a pasta www/html

**Comment by marciocelebri** [comment]
@mauri870 já dei permissão total a pasta 777. Não é problema de permissão não.

**Comment by mauri870** [comment]
Estranho... Uso sempre aqui desde que o installer estava no meu repo e sempre funcionou, inclusive nos testes de integração contínua do travisCI também... 
Setou permissão recursiva usando a opção -R no chmod?
Procura reinstalar o package e veja se corrige teu problema.
Executa esse comando:

```
composer g remove artesaos/laravel-installer && composer g install artesaos/laravel-installer
```

**Comment by marciocelebri** [comment]
Vou realizar o processo novamente. Dei permissão recursiva sim. Fazer o teste aqui e já informo.

**Comment by mauri870** [comment]
Faz muitos meses que não usava o apache, fui ver aqui e realmente deu o mesmo erro que você

**Comment by marciocelebri** [comment]
Pois é, removi e agora surgem outros erros. Continuarei acompanhando...

**Comment by mauri870** [comment]
Nas outras pastas tu consegue criar normal o projeto né?

**Comment by marciocelebri** [comment]
Via laravel new não consigo criar nada. Antes conseguia, porém com a versão 5.2. Depois removi, conforme instruído. Depois de instalar o laravel-installer artesaos não consegui mais. Dá o erro que lhe falei.

Via composer instalo normalmente o projeto. "composer create-project laravel/laravel blog "5.1.*"

**Comment by mauri870** [comment]
Eu estava recebendo o mesmo erro que você na pasta do apache. Rodei `chmod -R 777 /var/www/html/` e o problema cessou

**Comment by marciocelebri** [comment]
Aqui continua o erro. Mesmo dando um chmod -R 777 /var/www/html. Tentei, inclusive, rodar laravel new blog 5.1 na pasta home e mesmo assim não vai.

Chega até na hora de instalar as dependências e depois da o erro de Composer could not find a composer.json file.

**Comment by mauri870** [comment]
Teu composer está no path?

**Comment by marciocelebri** [comment]
Sim, está.

**Comment by marciocelebri** [comment]
![error](https://cloud.githubusercontent.com/assets/16846814/13115552/f94417ae-d576-11e5-8396-ad0e79df626b.jpg)

**Comment by mauri870** [comment]
Esse installer por enqunto é um wrapper pro composer create project, ele é quem faz a mágica acontecer. Estamos fazendo melhorias significativas no funcionamento dele agora, mas eu estou pra dizer que o teu composer não esta com permissão de escrita... Rodando um `ll /usr/local/bin/composer` ele tem que mostrar algo próximo a `lrwxrwxrwx`. Se não tiver assim coloca um chmod 777 no composer

**Comment by mauri870** [comment]
![captura de tela de 2016-02-17 14-13-16](https://cloud.githubusercontent.com/assets/10168637/13115854/b048e7c8-d580-11e5-8cbf-5d91f08ef48e.png)

**Comment by marciocelebri** [comment]
Talvez não seja problema de permissão. Olha aí:

![error-2](https://cloud.githubusercontent.com/assets/16846814/13115969/c7d74900-d578-11e5-9d08-59ab17e939cc.jpg)

**Comment by mauri870** [comment]
Vê pra mim se ele pelo menos cria a pasta da instalação. Por exemplo laravel new blog LTS, ele tem que criar a pasta blog pelo menos

**Comment by marciocelebri** [comment]
Dá o mesmo erro. Não cria a pasta.

**Comment by mauri870** [comment]
O problema é com algo na sua máquina... O composer não acha o caminho até a pasta pois ela não foi criada... Logo ele procura em um dir acima, no caso na pasta html e não encontra o composer.json. Eu utilizo o Symfony/Proccess pra rodar os comandos na máquina, que seria o mesmo que rodar no terminal, mas infelizmente pra você o create project que está rodando no interior do installer não está funcionando...

Basicamente o resultado do método [`getInstallationCommand`](https://github.com/artesaos/laravel-installer/blob/master/src/NewCommand.php#L138-L161) é +- isso:

``` bash
composer create-project laravel/laravel /home/mauri870/laravel_projects/packages/laravel-installer/blog "5.1.*" --prefer-dist
```

Claro que pra ti vai mudar, mas tenta substituir o caminho de instalação por /var/www/html/blog e ver se funciona

**Comment by marciocelebri** [comment]
@mauri870 Com esse comando, agora funcionou.

**Comment by mauri870** [comment]
Mas é exatamente isso que o Proccess do symfony roda ┻━┻︵ (°□°)/ ︵ ┻━┻

**Comment by marciocelebri** [comment]
Porém, via laravel-installer não vai. laravel new blog não vai. Pois é! Ficou na mesma.

**Comment by mauri870** [comment]
Se tu quiser pode requerer o dev-master e ver se muda algo, lá está estável também. 

```
composer g require artesaos/laravel-installer:dev-master
```

Vou tentar fuçar aqui pra entender por que raios pra vc esta acontecendo isso

**Comment by marciocelebri** [comment]
Também não! Obrigado @mauri870 qualquer novidade só informar.
